swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
paths:
  /accounts/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transaction API
      description: API for fetching transactions for an account
      parameters:
        - in: path
          name: accountId
          description: Unique ID of account
          required: true
          type: string
      responses:
        '200':
          description: Transactions for account retrieved successfully
          schema:
            $ref: '#/definitions/accountApiResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Account not found
        '500':
          description: Internal Server Error

  /transactions/{accountId}/{transactionId}/{item}:
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transaction API
      description: API for updating category in transaction
      parameters:
        - in: path
          name: accountId
          description: Unique ID of account
          required: true
          type: string
        - in: path
          name: transactionId
          description: Unique ID of transaction
          required: true
          type: string
        - in: path
          name: item
          description: Category or note
          required: true
          type: string
        - in: body
          name: body
          description: Select category or write a note for this transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionCategoryNote'
      responses:
        '200':
          description: Request succeeded.
          schema:
            $ref: '#/definitions/CategoryApiResponse'
        '201':
          description: The request succeeded, and a new resource was created as a result.
          schema:
            $ref: '#/definitions/NoteApiResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized Access
        '403':
          description: Forbidden Access
        '404':
          description: Account not found
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transaction API
      description: API for deleting category in transaction
      parameters:
        - in: path
          name: accountId
          description: Unique ID of account
          required: true
          type: string
        - in: path
          name: transactionId
          description: Unique ID of transaction
          required: true
          type: string
        - in: path
          name: item
          description: Category or note
          required: true
          type: string
      responses:
        '200':
          description: Deleted successfully.
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized Access
        '403':
          description: Forbidden Access
        '404':
          description: Account not found
        '500':
          description: Internal Server Error

definitions:
  TransactionCategoryNote:
    properties:
      item:
        type: string

  accountApiResponse:
    type: object
    properties:
      transactions:
        type: object
        properties:
          transaction:
            type: object
            properties:
              date:
                type: string
              description:
                type: string
              amount:
                type: string
              balance:
                type: number

  CategoryApiResponse:
    type: object
    properties:
      status:
        type: number
      message:
        type: string
      category:
        type: string

  NoteApiResponse:
    type: object
    properties:
      status:
        type: number
      message:
        type: string
      note:
        type: string

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
